### ISSUE TITLE
no setting page in OptionsPage

### ISSUE THREAD

**Issue by xianting77** [vivaladav/BitsOfBytes#4]
Seems can not see the setting page on OptionsPage. set QT_DEBUG_PLUGINS =1 ,add  qDebug() to trace loading work flow, seems can not go to QWidget *OptPageMain::widget(), can you reproduce this issue? if yes, how to resolve it? thanks for your time.
[](url)

**Comment by vivaladav** [comment]
I guess you're referring to the qtctimer project.

Probably your problem is that you're not setting the right environment variables in your project:
- QTC_SOURCE – path to the source code of Qt Creator
- QTC_BUILD – path to the build directory of Qt Creator

You can follow my [blog post](http://blog.davidecoppola.com/2019/12/how-to-create-a-qt-creator-plugin/) for more info.

**Comment by xianting77** [comment]
Hi  
Thanks for your sharing.
the problem can be fixed by addingaddAutoReleasedObject(mOptionsPage); in boolQtCTimerPlugin::initialize( ) after mOptionsPage=newOptPageMain(mSettings,this);
It seems the OptionPage object can be added into object pool by this line.


FYI
Thanks again












在 2020-10-23 11:41:50，"Davide Coppola" <notifications@github.com> 写道：

Closed #4.
